### ISSUE TITLE
No module named 'distutils'

### ISSUE THREAD

**Issue by aceliuchanghong** [AuvaLab/itext2kg#2]
第一步就报错安装不了
import distutils.core
ModuleNotFoundError: No module named 'distutils'

**Comment by lairgiyassir** [comment]
Hello, 

Could you please provide us with the full traceback of the error? 

Thank you ;)

**Comment by aceliuchanghong** [comment]
> Hello,
> 
> Could you please provide us with the full traceback of the error?
> 
> Thank you ;)

thankyou~

**Comment by aceliuchanghong** [comment]
thankyou for your help.
- first i run
(.venv) (base) PS D:\aProject\py\all_temp> pip install setuptools 
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: setuptools in d:\aproject\py\all_temp\.venv\lib\site-packages (74.1.2)

- but then
(.venv) (base) PS D:\aProject\py\all_temp> pip install itext2kg                                 
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting itext2kg
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/52/e8/1c3da1a648b4a55a0143ce12877452b4fff334550ef464eca43a658174cb/itext2kg-0.0.3-py3-none-any.whl (31 kB)
Collecting langchain==0.1.10 (from itext2kg)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/45/41/b496afcf4338c92c7661fd2f77097999389c966bee09c7875ac982424e46/langchain-0.1.10-py3-none-any.whl (806 kB)
Collecting langchain-core==0.1.28 (from itext2kg)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f4/55/c1b8fff498cfd7939491ea6c2322c4187da5fb2b3baf52fe4688775a50b0/langchain_core-0.1.28-py3-none-any.whl (252 kB)
Collecting langchain-openai==0.0.8 (from itext2kg)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/81/63/012be16114559243aabcc9ec570366df84591dc9f8f3c2349a398e9b3626/langchain_openai-0.0.8-py3-none-any.whl (32 kB)
Collecting neo4j==5.24.0 (from itext2kg)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ba/16/53e963b15cf08d62e521fe70feccc36e9a718617e483b0b132aeffd86072/neo4j-5.24.0-py3-none-any.whl (294 kB)
Collecting numpy==1.24.4 (from itext2kg)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a4/9b/027bec52c633f6556dba6b722d9a0befb40498b9ceddd29cbe67a45a127c/numpy-1.24.4.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "d:\aProject\py\all_temp\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "d:\aProject\py\all_temp\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "d:\aProject\py\all_temp\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "d:\aProject\py\all_temp\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\liuch\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\liuch\AppData\Local\Temp\pip-build-env-bn9mos8l\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\liuch\AppData\Local\Temp\pip-build-env-bn9mos8l\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\liuch\AppData\Local\Temp\pip-build-env-bn9mos8l\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


- third
(.venv) (base) PS D:\aProject\py\all_temp> python --version
Python 3.12.3

maybe it's windows-env problem,though i failed at ubuntu ethier,QAQ

**Comment by lairgiyassir** [comment]
It appears that the error arises because numpy 1.24 is incompatible with newer Python versions, such as 3.12. 

As a temporary solution, please consider downgrading your Python version to 3.11. I will also update the iText2KG requirements to address this issue. 

Tell me if this resolves your error.
