### ISSUE TITLE
An error occurred during   from itext2kg import DocumentDistiller

### ISSUE THREAD

**Issue by againcui** [AuvaLab/itext2kg#27]
Hello：
when i import DocumentDistiller,The following error message is displayed  ' ValueError: no signature found for builtin <built-in function array>'
How can I solve it,  thanks!

**Comment by lairgiyassir** [comment]
Hello, 

Could you provide the full traceback of the error? 
Thank you

**Comment by againcui** [comment]
> Hello,
> 
> Could you provide the full traceback of the error? Thank you

The following is, thank you very much for your hard work
***************************************************************************************************************************
Traceback (most recent call last):
  File "/data/home/zewen.cui/GraphRAG/iText2KG_czw/run.py", line 5, in <module>
    from itext2kg import DocumentDistiller
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/itext2kg/__init__.py", line 1, in <module>
    from .documents_distiller import DocumentsDistiller
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/itext2kg/documents_distiller/__init__.py", line 1, in <module>
    from .documents_distiller import DocumentsDistiller
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/itext2kg/documents_distiller/documents_distiller.py", line 2, in <module>
    from ..utils import LangchainOutputParser
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/itext2kg/utils/__init__.py", line 3, in <module>
    from .matcher import Matcher
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/itext2kg/utils/matcher.py", line 4, in <module>
    from ..models import Entity, Relationship
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/itext2kg/models/__init__.py", line 1, in <module>
    from .knowledge_graph import Entity, Relationship, KnowledgeGraph
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/itext2kg/models/knowledge_graph.py", line 6, in <module>
    class EntityProperties(BaseModel):
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 226, in __new__
    complete_model_class(
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 658, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/main.py", line 702, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 612, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 881, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 693, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 693, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1073, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1265, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2062, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2137, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/functional_validators.py", line 837, in __get_pydantic_core_schema__
    original_schema = handler(source)
                      ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2043, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 977, in match_type
    return self._call_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1818, in _call_schema
    sig = signature(function)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/inspect.py", line 3263, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/inspect.py", line 3011, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/inspect.py", line 2528, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/GraphRAG/lib/python3.11/inspect.py", line 2326, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in function array>

**Comment by wenjiezy** [comment]
itext2kg/models/knowledge_graph.py

**Comment by lairgiyassir** [comment]
I think this is an error coming from pydantic. The same issue was reported here #26
